### ISSUE TITLE
Feature Request List

### ISSUE THREAD

**Issue by NathanaelA** [iliasbhal/nativescript-react#2]
A couple of your items on your feature request list might be already handled and/or moot points.

1. setTimeout/setInterval is the NativeScript way to do it; those wrap the native implementation on both platforms; no reason to redo that code.  Just use set/clear  Timeout/Interval...

2. DOM access; you might checkout my Nativescript-Dom plugin; it adds several DOM  features; (i.e. getElementBy* and ClassList.*)  -- Not 100% sure if this is what you are referencing; but that code is available.

**Comment by iliasbhal** [comment]
@NathanaelA  🎉 thanks for the feedback, I updated the Readme.md.
I'll work with you to use the nativescript-dom package within nativescript-react. ;)
